### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by maelvalais** [maelvalais/homebrew-amc#1]
![amc-en](https://user-images.githubusercontent.com/2195781/34616703-4ef9a912-f239-11e7-82ec-256acf855104.png)
![amc](https://user-images.githubusercontent.com/2195781/34616707-513422e8-f239-11e7-90db-a8910062d563.png)

**Comment by maelvls** [comment]
![Screenshot 2021-12-04 at 11 13 05](https://user-images.githubusercontent.com/2195781/144706032-0e974243-d99d-47c9-93a7-e3a7a15a6a85.png)
