### ISSUE TITLE
Reduce window to dock appears to be not working

### ISSUE THREAD

**Issue by chfarges** [maelvalais/homebrew-amc#18]
Hello and first of all, congratulations for your work. AMC installed well and appears to work fine. I have however a small issue. When I try to reduce the window to dock using the "-" button at top right of the app window, nothing happens (closing and fullscreen buttons work). I installed the devel version on MacOS Mojave. Thanks !

**Comment by maelvalais** [comment]
Hi,

First off, thank you for using the Homebrew formula and for reaching out here! 🙂

I'll try to investigate this 'reduce button' issue ; it is probably related to the UI library (Glade) used with Gtk3 in the 1.4.0 version and the fact that the Gtk3 backend to xquartz for macOS is quite buggy/lags behind.

The same weird/buggy behavior occurs with other apps using this layout, e.g., Glade itself (try `brew install glade`)

I don't really know how to deal with this bug... 😕

**Comment by chfarges** [comment]
Thank you for your fast feedback ! Not a big issue anyway. I do not remember if I had the problem on the MacPorts version (I did a clean install of Mojave and as there is no MacPorts installer for Mojave, I gave a try to Homebrew and to your formula).

**Comment by chfarges** [comment]
And by the way, I just noticed that this Homebrew version of AMC is displayed like a retina application on my Mac (with MacPorts, it was all blurry). Good point for the Homebrew version ;-)

**Comment by maelvalais** [comment]
Hi!
I'll be closing this one as I can't really do anything about that particular bug. I added a notice in the `README` about that issue so that people can know.
Thanks!
