### ISSUE TITLE
How to get the latest development version

### ISSUE THREAD

**Issue by chfarges** [maelvalais/homebrew-amc#21]
Hello,
I saw that a new version (rc2) is available. I am on rc1_2. However, when running `brew update`, there is nothing to update. I tried to uninstall rc1_2 but when running `brew install maelvalais/amc/auto-multiple-choice --devel` it is still version 1_2 that installs.
I am new to Homebrew so may be I do something wrong ?
Thanks for your help !

**Comment by maelvalais** [comment]
Hi! I just updated the whole thing, separating the standard stable formula from the devel version.

Instead of using `--devel`, you can use

    brew install auto-multiple-choice-devel

which will use a pre-built binary (so much faster)

**Comment by maelvalais** [comment]
You will have to `brew unlink auto-multiple-choice` before doing so, otherwise the formulas `auto-multiple-choice` and `auto-multiple-choice-devel` will conflict ("linkage error" or something like that)

**Comment by chfarges** [comment]
Hello ! I installed the new version following your recommandations and it works perfectly ;-) Thanks !

**Comment by maelvalais** [comment]
Perfect!
