### ISSUE TITLE
Problem to export Notes

### ISSUE THREAD

**Issue by GizmoBen** [maelvalais/homebrew-amc#6]
Hello,

First of all, thank you very much for your work on AMC ;-). I don't know if my problem comes from the installation on Mac OS X High Sierra or an accent in the example I used to create my test... I used AMC successfully to generate the test, scan it but I cannot export it...

I used the template "Préremplies-ensemble.tex" so it tries to create a Préremplies-ensemble.csv but I get the following message : 

"L'export des notes dans le fichier /../Préremplies-ensemble.csv n'a sans doute pas fonctionné, car ce dernier fichier est inexistant..."

I post my question here because I wonder if it comes from High Sierra specifically... Is there a way to retrieve the results manually in cause I cannot solve the export problem ?

**Comment by maelvalais** [comment]
Hi! Thanks for reaching out!
I'll try to reproduce and get back to you asap.

**Comment by maelvalais** [comment]
Can you detail the steps you took in order to get this error?

**Comment by maelvalais** [comment]
Oui, 🇫🇷 !
Parles-tu de l'accent de `/../Préremplies-ensemble.csv` ?

**Comment by maelvalais** [comment]
Bizarre, dans les tarballs que j'utilise pour Homebrew les fichiers s'appellent bien `Preremplies-ensemble.tex` ; je suppose qu'effectivement le souci vient de là ?

Il me faudrait un "minimal working example" pour pouvoir reproduire le bug je pense :( Mais vu que c'est un énoncé d'exam passé, ça va être difficile

Je pense que cette histoire d'accent vient de `options.xml` (dans le dossier du projet AMC). Pourrais-tu me montrer ce fichier s'il ne contient aucune info sensible ? (utilise \`\`\` pour que ça apparaisse en mode 'code' -- [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/))

**Comment by GizmoBen** [comment]
Ok je pensais avoir supprimé l’accent moi-même car je ne comprenais pas que celui-ci ai pu réapparaitre… Quand je faisais le test concluent c’était sur les fichiers « ensemble.tex » 

Si vous voulez je suis prêt à vous transmettre l’entièreté du dossier si vous m’en garantissez la confidentialité par mail car il s’agit là uniquement d’un QCM qui compte pour 5% de la note finale des étudiants… Rien de critique !

Voici déjà le options.xml

**Comment by GizmoBen** [comment]
ps : le PDF contenant les copies corrigées est généré sans aucun souci

**Comment by maelvalais** [comment]
Ok, pas de soucis ! mael.valais@gmail.com

**Comment by maelvalais** [comment]
Je crois que les pièces jointes ne marchent pas quand on envoie en
répondant aux emails de Github ; il faut aller sur l'issue et drag-drop les
pièces. Sinon m'envoyer par email directement

**Comment by maelvalais** [comment]
For anyone wondering: this was a problem with the accent used in "examination code" in Parameters > Project > Code (short name) for examination. Removing the accent `é` should fix the issue.
